### ISSUE TITLE
 unexpected keyword argument 'capture_output'

### ISSUE THREAD

**Issue by yashasolutions** [adefossez/seewav#2]
```
Traceback (most recent call last):
  File "/home/user/.local/bin/seewav", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.6/site-packages/seewav.py", line 297, in main
    size=(args.width, args.height))
  File "/home/user/.local/lib/python3.6/site-packages/seewav.py", line 179, in visualize
    wav, sr = read_audio(audio, seek=seek, duration=duration)
  File "/home/user/.local/lib/python3.6/site-packages/seewav.py", line 66, in read_audio
    info = read_info(audio)
  File "/home/user/.local/lib/python3.6/site-packages/seewav.py", line 54, in read_info
    capture_output=True)
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'
```

Could be linked to : 
https://stackoverflow.com/questions/53209127/subprocess-unexpected-keyword-argument-capture-output

**Comment by yashasolutions** [comment]
Dependency to Python 3.7
ok, so I fixed it 
- install python 3.7
`sudo apt-get install python3.7`
- install python3.7-dev
`sudo apt-get install python3.7-dev`
- install specifying python3.7
`python3.7 -m pip install seewav`

and then it works

**Comment by adefossez** [comment]
Yes, you need Python 3.7. I updated the readme to make that clear :)
